describe('add bookmark', () => {
    it('passes', () => {
      cy.visit('http://localhost:3001')
      cy.wait(2000)
      cy.get("svg[data-icon='user']").click()
      cy.wait(2000)
      cy.get("input[id='signInUsername']").type("User1")
      cy.wait(2000)
      cy.get("input[id='signInPassword']").type("User1")
      cy.wait(2000)
      cy.get("button[id='connection']").click()
      cy.wait(2000)
      cy.contains("Welcome User1")
      cy.wait(2000)
      cy.get("div.TopArticle_topContainer__TEXEF > div > svg").click()
      cy.wait(2000)
      cy.get("div.Header_linkContainer__hNrE8 > span:nth-child(2)").click()
      cy.wait(2000)
      cy.get("#__next > div > div > div > div")
      cy.wait(2000)
    })
  })